### ISSUE TITLE
how to get offset values for each iana timezones?

### ISSUE THREAD

**Issue by sajeetharan** [mj1856/TimeZoneConverter#10]
Currently i am doing the following,

 
            foreach (var timeZone in TZConvert.KnownIanaTimeZoneNames)
            {
               
                returnList.Add(new TimeZoneDto
                {
                    Code = timeZone,
                    Name = timeZone

                });
            }
 

how can i get the offset value for each time zone inside the loop? is there an existing method ?

**Comment by sajeetharan** [comment]
Update, i tried this

 foreach (var timeZone in TZConvert.KnownIanaTimeZoneNames)
 {
                var tzi = TZConvert.GetTimeZoneInfo(timeZone.ToString());
                TimeSpan offset = tzi.GetUtcOffset(DateTime.Now);
                ....
}

but  TZConvert.GetTimeZoneInfo(timeZone.ToString()); it does not work for all timezone values.

**Comment by mj1856** [comment]
Hi.  I answered the why it doesn't work for all values [in your StackOverflow question](https://stackoverflow.com/a/47837698/634824).

As far as a solution for getting all offsets, do understand that you can only get the offset for a specific time (you have `DateTime.Now` - though `UtcNow` would be more appropriate).  Offsets change over time within a single time zone - like how US Pacific Time is sometimes UTC-8 and sometimes UTC-7 for daylight saving time.

You can certainly just get the current offsets of the time zones installed on the machine without any libraries at all:

```csharp
DateTime now = DateTime.UtcNow;
foreach (var timeZone in TimeZoneInfo.GetSystemTimeZones())
{
    TimeSpan offset = timeZone.GetUtcOffset(now);
    Console.WriteLine(offset + " " + timeZone.Id);
}
```

If you want to *not* rely on the time zones installed on the system, then use [Noda Time](https://nodatime.org):

```csharp
Instant now = SystemClock.Instance.GetCurrentInstant();
foreach (string id in DateTimeZoneProviders.Tzdb.Ids)
{
    DateTimeZone tz = DateTimeZoneProviders.Tzdb[id];
    Offset offset = tz.GetUtcOffset(now);
    Console.WriteLine(offset + " " + id);
}
```
