### ISSUE TITLE
America/Indiana/Indianapolis

### ISSUE THREAD

**Issue by jiodice** [mj1856/TimeZoneConverter#13]
Hello,

I am using this library in combination of GeoTimeZone to take a lat/long and get back a Windows time zone.
When I pass in a lat/long from an East Indiana address into GeoTimeZone I get back "America/Indiana/Indianapolis"
When I use TimeZoneConvert to convert that IANA to a Windows time zone I get back US Eastern Standard Time instead of Eastern Standard Time. The difference being US Eastern Standard Time does not observe DST which Indiana did away with in 2006.
https://www.timeanddate.com/time/us/indiana-time.html

IANA shows 'America/Indiana/Indianapolis' as observing DST same as normal Eastern Standard Time

**Comment by mj1856** [comment]
Hi.  Sorry for the delayed response.

The Windows ID "US Eastern Standard Time" is indeed the correct one to use for Indiana.  It's English display name on Windows is "Indiana (East)".  If you examine the Dynamic DST registry keys, you'll see that the only difference is that it doesn't have DST for 2005 and prior.  For 2006 and newer they are identical.

This corresponds to the the data shown for Indianapolis here:
https://www.timeanddate.com/time/zone/usa/indianapolis?syear=2000&eyear=2010

You'll also find a long history of time in Indiana here:
https://en.wikipedia.org/wiki/Time_in_Indiana, which this is described in detail.

This is also reflected in the [CLDR's mapping file](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) as well, so the mapping is correct.
