### ISSUE TITLE
Over 13000% slower than BCL and over 54000% slower than NodaTime

### ISSUE THREAD

**Issue by CShepartd** [mj1856/TimeZoneConverter#14]
I checked how long will take timezone convert with BCL `TimeZoneInfo`, `NodaTime` and `TZConvert` in `.Net Core`. Just look

```
BCL TimeZoneInfo 1579,552 ms 
NodaTime 382,9316 ms 
TZConvert 207779,6301 ms  
```

>h-h-how?

Normally
```
for (int i = 0; i < 1000000; i++)
{
    var a = TimeZoneInfo.ConvertTime(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Central European Standard Time"));
}
```
```
for (int i = 0; i < 1000000; i++)
{
    var a = Instant.FromDateTimeUtc(DateTime.UtcNow).InZone(DateTimeZoneProviders.Tzdb["Europe/Warsaw"]).ToDateTimeUnspecified();
}
```
```
for (int i = 0; i < 1000000; i++)
{
    var a = TimeZoneInfo.ConvertTime(DateTime.UtcNow, TZConvert.GetTimeZoneInfo("Europe/Warsaw"));
}
```

I thought this is a joke but no. Dont ask me about environment cuz i tested on several machines on Windows 10 x64.  Just test yourself

Summary: 
BCL `TimeZoneInfo` is over 130x faster than `TZConvert`
`NodaTime` is over 540x faster than `TZConvert`

**Comment by mj1856** [comment]
"Lightweight" typically refers to size, not perf.  If you would like to revise your issue to be less hostile, I'd be happy to look into improving performance.  Better yet, a PR would be appreciated. 

Otherwise, all I'm hearing is "F*$% you, I don't like this" - and really that doesn't motivate me much.

**Comment by CShepartd** [comment]
"Lightweight" typically refers to size and performance (cuz it should be connected). I only showing a big problem about this project

> and really that doesn't motivate me much
Publishing a library / nuget packege it's not about motivating or demotivating. It's also not about you. It's about this "monster" itself with is horrible slow. I can change name of this issue to better describe problem. This issue should be closed when come close to BCL (now slower than 13000%, just imagine it)

**Comment by mj1856** [comment]
Closing due to nonconstructive nature of this discussion.
