### ISSUE TITLE
Does not yet support "Saratov Standard Time"

### ISSUE THREAD

**Issue by DavidEHerbst** [mj1856/TimeZoneConverter#2]
The new "Saratov Standard Time" time zone is not yet supported.  See [Windows Time Data Updates for Tonga, Northern Cypress, Mongolia and Saratov (Russia) is now available](https://blogs.technet.microsoft.com/dst2007/2017/03/21/windows-time-data-updates-for-northern-cypress-mongolia-and-saratov-russia-is-now-available/)

**Comment by mj1856** [comment]
This is added as of release `1.1.0`.  Thanks!

**Comment by DavidEHerbst** [comment]
Thanks for the fast turnaround!

**Comment by mj1856** [comment]
Also note I pushed a small update today in release 1.1.1 as I missed a few things yesterday.  Thanks.
