### ISSUE TITLE
Exception in GetTimeZoneInfo on upgrade

### ISSUE THREAD

**Issue by Azsael** [mj1856/TimeZoneConverter#20]
I upgraded from 2.2.1 to 2.3.2 and getting the following error when tests are run in my build server.

**Stack Trace:**
System.InvalidTimeZoneException : "Etc/GMT" was not recognized as a valid Windows time zone ID.
Stack Trace:
at TimeZoneConverter.TZConvert.WindowsToIana(String windowsTimeZoneId, String territoryCode)
at TimeZoneConverter.TZConvert.GetTimeZoneInfo(String windowsOrIanaTimeZoneId)

Any ideas while this error happens?

**Comment by mj1856** [comment]
Can you tell me more about the environment of your build server?  Thanks.

**Comment by Azsael** [comment]
Hey mj!

Sorry for the delayed response.

The build is run inside a docker container as part of Visual Studio Team Services Agent, which is running in a ec2 instance running Ubuntu.

The particular agent is microsoft/vsts-agent:ubuntu-16.04-docker-17.06.0-ce-standard (https://hub.docker.com/r/microsoft/vsts-agent/)

I am running Windows locally so it is a bit difficult to replicate the issue locally.

**Comment by mj1856** [comment]
This should be fixed now in version 2.4.0.   Thanks.
