### ISSUE TITLE
Västeuropa, sommartid" was not recognized as a valid Windows time zone ID. System.InvalidTimeZoneException at TimeZoneConverter.TZConvert.WindowsToIana

### ISSUE THREAD

**Issue by sajeetharan** [mj1856/TimeZoneConverter#22]
This library works perfectly on local, but in production it throws the above issue.

Västeuropa, sommartid" was not recognized as a valid Windows time zone ID. System.InvalidTimeZoneException at TimeZoneConverter.TZConvert.WindowsToIana

the logic i have implemented here is "get the user timezone from the machine" and convert it to corresponding iana timezone.

what is wrong here?

**Comment by mj1856** [comment]
Well, indeed that's not a valid time zone id.   Can you show the code where you obtain it?

**Comment by mj1856** [comment]
Yeah, can't help you there.  Sorry.
