### ISSUE TITLE
Support transforming time zone Ids when format unknown?

### ISSUE THREAD

**Issue by martincostello** [mj1856/TimeZoneConverter#25]
I was writing some code to convert Windows time zone Ids to IANA time zone Ids, which is fine and works, as that's the format they're currently expected to be in.

But as an edge case I added a test case to validate that if an IANA time zone was passed in to my method, it returned the original IANA time zone to isolate myself from possible future changes in the source of the time zone data I'm consuming. However, this causes an `InvalidTimeZoneException` to be thrown because the input isn't already a Windows time zone.

Is this something `TZConvert` should support natively (I'm happy to do a PR if so), or is this something you think should be catered for by the package consumer?

Effectively this is to create an equivalent of `TZConvert.GetTimeZoneInfo()` where the caller only wants an ID in one format or the other, and doesn't actually need the `TimeZoneInfo` object.

**Comment by mj1856** [comment]
The Try APIs were added in 2.4.0.  See if that makes things easier for you. :)

**Comment by mj1856** [comment]
Closing this request.  Hopefully the new APIs solved the problem.  Thanks.
