### ISSUE TITLE
System.TimeZoneNotFoundException thrown using dot net core application on Linux for getting TimeZoneInfo

### ISSUE THREAD

**Issue by adhikaribi** [mj1856/TimeZoneConverter#26]
Hi,

I have developed a simple dot net core application to validate timezone mapping for the list of timezone we have in our database. The main idea here is to make this Timezone mapping platform agnostic.  Most of the timezone string are mapped correctly while running this app on Linux except fewer to mention, like `UTC+12, UTC-08, UTC-02, UTC-11, UTC-09, Mid-Atlantic Standard Time and Dateline Standard Time` 

It throws `System.TimeZoneNotFoundException` while running this piece of code `TZConvert.GetTimeZoneInfo(tzString)` on those timezone string mentioned above.
This works completely fine while running on my local Windows dev environment.

So my question, is this a bug or there is a workaround to this (which I am missing) to fix this problem. Am I suppose to create a static mapping dictionary for this? which I am not in total favor of but if nothing works that would be my last solution to it.

Latest Library Version `TimeZoneConverter` library v2.3.2

Please let me know how to procced on this,

Thanks

**Comment by adhikaribi** [comment]
@mj1856 Have you seen this yet?

**Comment by mj1856** [comment]
Thanks for the report, and sorry for the delay.  This sounds like the same problem reported in #21.  I'm investigating still, but hope to have a fix soon.

Thanks for your patience.

**Comment by mj1856** [comment]
This is fixed in 2.4.0. It was related to how the `TimeZoneInfo.GetSystemTimeZones` method behaves on non-Windows systems.
