### ISSUE TITLE
The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.

### ISSUE THREAD

**Issue by tarekgh** [mj1856/TimeZoneConverter#28]
_From @liguangkk on April 25, 2018 13:39_

I got this error on aws lambda.
The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
"errorMessage": "An item with the same key has already been added. Key: Canada/East-Saskatchewan",

_Copied from original issue: dotnet/corefx#29325_

**Comment by tarekgh** [comment]
@mj1856  could you please look to know if this issue is because of TimeZoneInfo enumeration or it is TimeZoneConverter issue? Thanks.

**Comment by tarekgh** [comment]
https://github.com/mj1856/TimeZoneConverter

**Comment by tarekgh** [comment]
_From @mj1856 on April 25, 2018 17:41_

Yeah, should be logged on my repo, not here.  

@liguangkk, please log over there.  When you do, please give version and code to reproduce.  I thought I had addressed this one already.  Thanks.

**Comment by tarekgh** [comment]
@liguangkk could you please add the full stack? 

@mj1856 I looked briefly at your code, although I am not sure exactly what the problem is, could it be because of the line  

https://github.com/mj1856/TimeZoneConverter/blob/master/src/TimeZoneConverter/TZConvert.cs#L327

which looks we didn't encounter Canada/East-Saskatchewan before but now we do.

I'll move this issue to your repo. Thanks.

**Comment by mj1856** [comment]
Thanks @tarekgh for moving it with all the detail.

Yes, there's some weirdness around that time zone.  I had to add it in another situation, but it looks like I'll have to add it conditionally.

Basically, the tzdb almost never *removes* a zone, though sometimes they become links to other zones.  But in this case, for various technical reasons, it was removed.  But it still exists in the CLDR as an alias, and won't be removed there, so I need to honor it in this library.

(Time zones are indeed a mess! ) ;)

**Comment by mj1856** [comment]
@liguangkk - Please update to the latest version 2.4.1 and let me know if that solves the issue.

Also, if you have ability to update your tzdata release in your environment, you should. ;)

**Comment by mj1856** [comment]
Sorry, but I don't see anything in this stack trace that involves TimeZoneConverter.  Rather, it looks like you're creating a custom time zone?  Hard to tell without code.

**Comment by tarekgh** [comment]
it looks trying to create a custom zone and passing wrong adjustment rules to it. the exception message is descriptive.
