### ISSUE TITLE
International Date Line West TimeZoneNotFoundException

### ISSUE THREAD

**Issue by markand911** [mj1856/TimeZoneConverter#30]
I am extensively using this library.
But recently started receiving this exception.
Exception of type 'System.TimeZoneNotFoundException' was thrown.

The timezone i use to get timezone info is "International Date Line West" which is actually UTC-11.

Am I using incorrect timezone?

**Comment by mj1856** [comment]
(Sorry for the delayed response.)

Yes, it appears you are using invalid strings.

There is a Windows time zone who's *display name* is `(UTC-12:00) International Date Line West`.  Its ID is `Dateline Standard Time`, and it is in UTC-12.

There is a different time zone for UTC-11, whose display names is `(UTC-11:00) Coordinated Universal Time-11`.  Its ID is simply `UTC-11`.

In either case, you want to pass the ID, not the display name.  Display names are localized by OS user language.  For example, a user with French local would see something like `ligne de date internationale ouest` for the display name, but would still use `Dateline Standard Time` for the ID.
