### ISSUE TITLE
Missing iana value

### ISSUE THREAD

**Issue by lukapor** [mj1856/TimeZoneConverter#31]
Hi I have some test from converting iana codes to timezone id

Test fails on ian value Antarctica/Troll

I saw that value  missing in mapping file.

**Comment by mj1856** [comment]
Sorry for the delayed response.

Indeed, `Antarctica/Troll` is currently the *only* valid IANA time zone ID that is not mappable to Windows.  If you try to convert, you'll notice the exception message says:

```
Unhandled Exception: System.InvalidTimeZoneException: "Antarctica/Troll" was not recognized as a valid IANA time zone name, or has no equivalent Windows time zone.
```

In the case of `Antarctica/Troll`, the "... or has no equivalent Windows time zone" part applies.

**Comment by mj1856** [comment]
As to *why*, take a look at [the history of this time zone between 2005 and 2015](https://www.timeanddate.com/time/zone/antarctica/troll?syear=2000&eyear=2020).  You'll see there were three different offsets in each year. Windows time zones cannot support such complexity..
