### ISSUE TITLE
Cannot run in .NET 4.7.2

### ISSUE THREAD

**Issue by Kilowhisky** [mj1856/TimeZoneConverter#33]
When i try to install and run in a .NET 4.7.2 console application i get these errors:

```
FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
```
FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Here's the whole program:

```
class Program
    {
        static void Main(string[] args)
        {
            string tz = TZConvert.IanaToWindows("America/New_York");
            Console.WriteLine(tz);
        }
    }
```

The correct binding redirect is present:

```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

Also the reference to `System.Runtime.InteropServices.RuntimeInformation` has been installed as requied by the package.

![image](https://user-images.githubusercontent.com/7075666/44930211-6d536a80-ad12-11e8-8e13-f4aa45bbba42.png)

The file being referenced is present at the `Path`. 

the file itself has the following properties:
![image](https://user-images.githubusercontent.com/7075666/44930354-e5ba2b80-ad12-11e8-9537-5982aa21c6f2.png)

**Comment by Kilowhisky** [comment]
i was able to temporarily resolve the issue by removing the `publicKeyToken` on the binding redirect. I don't know why its freaking out considering that is the actual publicKeyToken for the assembly. 

Either day this sounds like a .NET freakout and nothing in this utility.... Closing.

**Comment by mj1856** [comment]
I can repro this on .NET 4.7.1 and .NET 4.7.2 when created in the older csproj (not PackageReference) style.  Reopening.

**Comment by mj1856** [comment]
Added a separate target for 4.7.1 to resolve this in version 2.4.2.  Thanks.

**Comment by ritesh-pangea** [comment]
@mj1856  Is this package supported for .Net Framework 4.7.2. If not Is it possible to add this version as well to the target framework?

**Comment by mj1856** [comment]
It should work.  Does it not?

**Comment by ritesh-pangea** [comment]
@mj1856  So when I upgraded my .Net framework from 4.6 to 4.7.2 I saw my packages.config updated with attribute requireReinstallation = true for the 2 nuget packes (TimeZoneNames and TimeZoneConverter). So I uninstalled and reinstalled the packages and I saw the attribute no more. I just smoke tested your nuget package by making a few calls and it worked fine with 4.7.2 eventhough the csproj does not have 4.7.2 in the list of target frameworks. So I am not sure but any possible unknown issues. My recommendation is to just add the target framework in the csproj

**Comment by mj1856** [comment]
Your experience is as expected.  The 471 target should also work for 472.   There's no purpose to add an additional target to the build unless there's something special required for that version and higher.

Ideally there would be only one target, but there are edge cases to handle, hence why there is any multi-targeting in this project at all.

Each target makes the build longer and the package size larger.  So, no - I will not be adding a special target for 472 when the 471 target satisfies the requirements.

**Comment by ritesh-pangea** [comment]
Thanks for your response @mj1856
