### ISSUE TITLE
Central European Timezone Mismatches

### ISSUE THREAD

**Issue by mposvar** [mj1856/TimeZoneConverter#34]
In testing several timezones in this library, it appears that a large percentage of major European cities are being mapped to the wrong European timezone. Currently looking at Berlin, Rome, Amsterdam. The mappings file seems to indicate these are all W. European Time, but googling these places indicates they are all Central European Time. Is this a known issue, or is the current mapping file just bad?

Edit: Here are the mappings I see in the file:
`W. Europe Standard Time    IT    Europe/Rome`

Should be:
`Central Europe Standard Time    IT    Europe/Rome`

**Comment by mposvar** [comment]
Seeing now that it is because Windows lists those cities with W. European time.

**Comment by mj1856** [comment]
Indeed, that is the correct mapping.  You can see the authoritative data in the CLDR [here](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml).

You're right that they are in Central Europe.  That's an example of bad naming on Microsoft's part.  I call out `W. Europe Standard Time` being poorly named in [the `timezone` tag wiki on StackOverflow](https://stackoverflow.com/tags/timezone/info), along with several other examples.
