### ISSUE TITLE
Remap Volgograd

### ISSUE THREAD

**Issue by mj1856** [mj1856/TimeZoneConverter#36]
https://blogs.technet.microsoft.com/dst2007/2018/10/11/time-zone-updates-for-volgograd-oblast-russia/

`"Europe/Volgograd"` will map to a new zone `"Volgograd Standard Time"` soon.

(Need to validate the new zone is released by Microsoft before updating.)

**Comment by garilla** [comment]
Looks like this update was released. Do you plan to add 'Volgograd Standard Time' any time soon?

**Comment by mj1856** [comment]
Indeed, the update was released in [KB4468323](https://support.microsoft.com/en-us/help/4468323) (for pre-Win10 supported OSs) on 2018-11-27 and [KB4469342](https://support.microsoft.com/en-us/help/4469342) (OS Build 17763.168 for Windows 10 / Server 2018) on 2018-12-05.  However, I want to give the updates some more time to propagate to users.

Currently there is no mechanism in TimeZoneConverter to ensure the system has the time zone update installed, so if I introduce a new time zone too early it might create problems for some folks.

I need to think more deeply about the timeline of how updates like these should be introduced.   For now, I'll have to use my intuition.  I think a least a week more.

**Comment by mj1856** [comment]
This is published in version 2.5.1.  Thanks.

**Comment by garilla** [comment]
Thank you, it works!
