### ISSUE TITLE
Running under Visual Studio Community on Mac throws exception looking up TimeZone

### ISSUE THREAD

**Issue by martin-slater** [mj1856/TimeZoneConverter#38]
I just tried running a solution that works on Windows fine on my OS X box and 

 TZConvert.WindowsToIana(System.TimeZoneInfo.Local.StandardName);

fails (my current timezone is reported as MSK).  A quick run through the System timezones shows this list as failing to be looked up. 

```
            foreach(var zone in System.TimeZoneInfo.GetSystemTimeZones())            
            {
                string mappedName;

                if(!TZConvert.TryWindowsToIana(zone.StandardName, out mappedName))
                {
                    System.Diagnostics.Debug.WriteLine(zone.StandardName);
                }

            }

````

GMT
EAT
CET
WAT
CAT
EET
+01
SAST
HST
AKST
AST
-03
-04
EST
CST
-05
MST
PST
-02
-01
NST
+08
+07
+10
+11
+05
NZST
+03
+00
+06
+12
+04
IST
+09
+0530
HKT
WIB
WIT
+0430
PKT
+0545
WITA
KST
+0630
+0330
JST
WET
AEST
ACST
+0845
+1030
AWST
-06
MSK
+13
+1245
-09
ChST
+14
-0930
SST
-11
-08
-10

**Comment by mj1856** [comment]
Use the `Id` property, not the `StandardName` property.
