### ISSUE TITLE
TypeInitializationException Could not load type 'System.Runtime.InteropServices.OSPlatform' from assembly 'mscorlib on DotNetCore 2.2

### ISSUE THREAD

**Issue by clmcgrath** [mj1856/TimeZoneConverter#39]
Doesn't seem to matter what i call i am getting a `TypeInitializationException`  trying to load  `System.Runtime.InteropServices.OSPlatform`

```
System.TypeInitializationException : The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
---- System.TypeLoadException : Could not load type 'System.Runtime.InteropServices.OSPlatform' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at TimeZoneConverter.TZConvert.TryWindowsToIana(String windowsTimeZoneId, String& ianaTimeZoneName)
   at DigitalParadox.EWS.SharedCalendar.Tests.ICSDateHelperTests.TimeZone_Resolves_From_Universal_ID(String timezoneId) in C:\Users\Chris McGrath\source\repos\DigitalParadox.EWS.CalendarSync\DigitalParadox.EWS.SharedCalendar.Tests\ICSDateHelperTests.cs:line 75
----- Inner Stack Trace -----
   at TimeZoneConverter.TZConvert..cctor()
```

**Comment by jnyrup** [comment]
Can you share a complete project hitting this issue?
I tried compiling a .net core 2.2 project using TimeZoneConverter 2.5.1 and ran it on Windows 10.
It didn't reproduce your issue.

**Comment by dot4qu** [comment]
I get the same issue but with `System.Runtime.InteropServices.RuntimeInformation.dll`. We've used this dll in our multi-project solution previously with no problems. Installing the TimeZoneConverter nuget upgraded it to the most recent nuget version (4.3.0), but then seems to complain about not being able to find the correct dll
```
Exception:
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 
```
Obviously not the exact same issue, but related. This is on a .NET Framework 4.6.2 project

**Comment by mj1856** [comment]
I've removed the dependency on System.Runtime.InteropServices.RuntimeInformation for all .NET Framework targets.  This should fix the problem.  Please try out release 3.0.0 and let me know if that resolves the issue.  Thanks.

**Comment by mj1856** [comment]
Closing this issue.  If you are still having problems, please let me know and I'll re-open it.  Thanks.
