### ISSUE TITLE
Add support for "Asia/Qostanay" IANA time zone

### ISSUE THREAD

**Issue by tommasobertoni** [mj1856/TimeZoneConverter#43]
The new time zone is not yet recognized by the library, which throws an `InvalidTimeZoneException` when trying to convert it to a Windows time zone.

Looks like the new time zone has been added last December (2018), with the 2018 release of the tz database: http://mm.icann.org/pipermail/tz-announce/2018-December/000053.html.

**Comment by mj1856** [comment]
Confirmed.  Thanks.

**Comment by mj1856** [comment]
This is fixed in version 3.0.0.  Thanks.

**Comment by tommasobertoni** [comment]
Thank you.
