### ISSUE TITLE
Qyzylorda Standard Time

### ISSUE THREAD

**Issue by Mertsch** [mj1856/TimeZoneConverter#45]
"Qyzylorda Standard Time" was not recognized as a valid Windows time zone ID.
Microsoft Windows [Version 10.0.17763.402]

`Qyzylorda Standard Time;300;(UTC+05:00) Qyzylorda;Qyzylorda Standard Time;Qyzylorda Daylight Time;[01:01:0001;12:31:2017;0;[1;00:00:00;1;1;];[1;00:00:00.001;1;1;];60;][01:01:2018;12:31:2018;60;[0;00:00:00;1;1;1;];[0;00:00:00;12;3;5;];];`

**Comment by mj1856** [comment]
Thanks for reporting.  This is related to a recently added zone.  Looks like an update is in order.  `Qyzylorda Standard Time` should map to `Asia/Qyzylorda`.

https://techcommunity.microsoft.com/t5/Daylight-Saving-Time-Time-Zone/Time-zone-updates-for-S%C3%A3o-Tom%C3%A9-and-Qyzylorda-Kazakhstan-are-now/ba-p/468197

https://support.microsoft.com/en-us/help/4490128/time-zone-changes-in-windows-for-sao-tome-and-principe-and-qyzylorda

https://support.microsoft.com/en-us/help/4490481

Looks like perhaps you were on an insider build?  Either way, sorry I didn't get this out sooner.

**Comment by mj1856** [comment]
Fixed in version 3.1.0.  Thanks!
