### ISSUE TITLE
Minor platform inconsistency with timezone name case

### ISSUE THREAD

**Issue by PaitoAnderson** [mj1856/TimeZoneConverter#46]
This works on macOS, but throws an exception on Windows:
`TZConvert.GetTimeZoneInfo("eastern standard time");`

**Comment by mj1856** [comment]
Are you sure?  I do not get an exception when I try this on Windows.  The internal dictionaries all use `StringComparer.OrdinalIgnoreCase`.

What target platform are you using? (.net core or .net framework, version, etc.)

**Comment by mj1856** [comment]
Actually, nevermind.  I can repro it.  Fix forthcoming...

**Comment by mj1856** [comment]
Fixed in version 3.1.0.  Thanks!

**Comment by PaitoAnderson** [comment]
Sweet! Thank you :)
