### ISSUE TITLE
Asia/Kamchatka maps to old windows timezone

### ISSUE THREAD

**Issue by tophallen** [mj1856/TimeZoneConverter#47]
Found this issue when running some tests, if I pass in the windows timezone id: `Russia Time Zone 11` to `ConvertWindowsToIana` I get `Asia/Kamchatka` -> but if I try to call `GetTimeZoneInfo` with `Asia/Kamchatka` I get `(UTC+12:00) Petropavlovsk-Kamchatsky - Old` (display name, the id is `Kamchatka Standard Time`) which hasn't been in effect for a while I'm pretty sure it's not a data issue - I found these matches:

Windows | territory | IANA Mappings
-- | -- | --
Kamchatka Standard Time | 1 | Asia/Kamchatka
Russia Time Zone 11 | 1 | Asia/Kamchatka
Russia Time Zone 11 | RU | Asia/Kamchatka Asia/Anadyr

So I guess my issue is, maybe there could be a way to deprecate timezones where they would explicitly map, but not be the default when parsing. I'm not sure the best solution for that. But it would be helpful as the offsets are different during DST (no longer practiced in the Russia Time Zone 11).

I'm on windows 10 1809 professional.

**Comment by mj1856** [comment]
Fixed in version 3.2.0.  Thanks for reporting!
