### ISSUE TITLE
does not yet support "Coordinated Universal Time"

### ISSUE THREAD

**Issue by datttit** [mj1856/TimeZoneConverter#48]
Coordinated Universal Time is not support :( . So funny because it is frequently used :D :D

**Comment by mj1856** [comment]
That's a display name, but not a valid *identifier*.  You can pass `"UTC"`, or any of the IANA forms `"Etc/UTC"`, `"Etc/GMT"`, etc.

**Comment by stefanovualto** [comment]
@mattjohnsonpint may I ask you, how you would do to return the current IANA Timezone of a windows computer?

Because the following code won't work for UTC (but others it should)
```csharp
var tz = TZConvert.WindowsToIana(TimeZone.CurrentTimeZone.StandardName);
```

**Comment by datttit** [comment]
You can find the same timezone but not like this timezone

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by stefanovualto** [comment]
Do you agree on using the code below to fix this issue then?

```
 var IANAtz = TZConvert.WindowsToIana(TimeZoneInfo.Local.Id);
```

PS: Sorry for the previous message

**Comment by mattjohnsonpint** [comment]
If you are running strictly on Windows, and you want the IANA ID, then yes.

Keep in mind that `System.TimeZone` is deprecated.  You should *always* use `Syatem.TimeZoneInfo` instead.
