### ISSUE TITLE
System.TimeZoneNotFoundException when calling TimeZoneConverter.TZConvert.GetTimeZoneInfo("Asia/Qyzylorda")

### ISSUE THREAD

**Issue by dmichael266** [mj1856/TimeZoneConverter#49]
We are currently using version 3.1.0 of the TimeZoneConverter library and we have the following code that loops through the IANA time zones, converting them into a list of .NET TimeZoneInfo objects.  The code seems to run fine on our development machines (running Windows 10).

When we deployed the code as an AppService in MS Azure, the catch block got triggered for the "Asia/Qyzylorda" time zone.  All other time zones appear to be working just fine.

We got passed the issue by simply adding .Where(m => m != "Asia/Qyzylorda) to KnownIanaTimeZoneNames.  Just figured I'd let you know we'd encountered the issue.

```
public IList<TimeZoneInfo> GetTimeZoneList()
{
     IList<TimeZoneInfo> timeZoneInfos = new List<TimeZoneInfo>();
     foreach (string timeZone in TimeZoneConverter.TZConvert.KnownIanaTimeZoneNames)
     {
         try
         {
             timeZoneInfos.Add(TimeZoneConverter.TZConvert.GetTimeZoneInfo(timeZone));
         }
         catch (Exception e)
         {
               Console.WriteLine("Timezone = " + timeZone + " error: " + e.Message);
         }
     }

     return timeZoneInfos;
}
```

**Comment by mj1856** [comment]
It would seem Azure App Service does not yet have [this update](https://techcommunity.microsoft.com/t5/Daylight-Saving-Time-Time-Zone/Time-zone-updates-for-S%C3%A3o-Tom%C3%A9-and-Qyzylorda-Kazakhstan-are-now/ba-p/468197) installed.   I will follow up with them.  Thanks for reporting.

**Comment by mj1856** [comment]
Here's what I've learned that I can report:

- Azure App Service (on Windows) gets its time zone data via the [Azure Guest OS](https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix) that it is built upon.

- Time zone updates are rolled out via [Azure Guest OS patches](https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-msrc-releases).  That shows last one was the March 2019 update, with [KB 4486459](https://support.microsoft.com/kb/4486459).

- [KB 4490128](https://support.microsoft.com/kb/4490128) which contains the newly created `"Qyzylorda Standard Time"` has not been rolled out yet, but is slated for the next set of updates (June 2019).

- After the Guest OS updates has the patches, Azure App Service will begin the process of rolling them out.  This process takes some time, and [is documented here](https://docs.microsoft.com/en-us/azure/app-service/overview-patch-os-runtime.

Thus, I can conclude that for cloud applications, if you are using TimeZoneConverter simply to translate names to/from your clients, then you can use the latest version.  But if you are using `TZConvert.GetTimeZoneInfo` or `TimeZoneInfo.FindSystemTimeZoneByID`, be careful when new time zones are introduced.  It may be worth waiting to update TimeZoneConverter until you can be certain the new time zone exists on your servers (or in App Service, in this case).

Alternatively, one could use [Noda Time](https://nodatime.org/), which ships its own IANA tzdb data.  Thus giving control back to you as far as [how and when time zone data is updated](https://nodatime.org/userguide/tzdb).

**Comment by dmichael266** [comment]
Thank you very much for the detailed investigation and response.  Greatly appreciated.
