### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by ericardezp** [mj1856/TimeZoneConverter#5]
System.IO.FileLoadException: 'Could not load file or assembly 'TimeZoneConverter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

Thanks

**Comment by mj1856** [comment]
I don't strong name any of my nuget packages.  If you want strong naming, there are several ways to do that yourself.

https://github.com/brutaldev/StrongNameSigner

https://github.com/oising/strongnaming

https://blog.maartenballiauw.be/post/2014/09/10/automatically-strong-name-signing-nuget-packages.html

**Comment by mj1856** [comment]
More on this:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/
