### ISSUE TITLE
Wikipedia TZ abbreviations

### ISSUE THREAD

**Issue by yzorg** [mj1856/TimeZoneConverter#53]
Wikipedia has abbreviations for timezone.

https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations

For an example of how they are used see: https://en.wikipedia.org/wiki/List_of_stock_exchange_trading_hours 

Would you accept a PR to map this list to the most common IANA name?  "Wikipedia abbreviation map"?  Maybe I could model it after the Posix library.

**Comment by yzorg** [comment]
There are many collisions and ambiguities in the Wikipedia timezone abbreviations.  I don't know Posix well enough to know if there were any ambiguities there.  Most ambiguities can be resolved with region (i.e. continent or ocean, top-level IANA name), or could return a list.

**Comment by mj1856** [comment]
Sorry, that is beyond the scope of this library.  There are just too many ambiguities, and we'd have to have a full tzdb implementation at runtime to map to a specific abbreviation.

**Comment by ArtKarp** [comment]
I wouldn't think this is a good idea.   Actually, it is a really bad idea.
Here is why...

Wikipedia is using a timezone like "EST" for US Eastern time.   EST only
means that the US Eastern time zone on an indicated date is in "standard"
time.  There is only ONE time zone. The time zone is US Eastern Time AKA
America_New_York. Determining Standard vs Daylight time has to do with
local laws and dates within a given year.  In Windows you will see the time
zone name of "Eastern Time (US & Canada).  While the list does show
"UTC-05:00", this is calculated base on the date of the day you view your
time zone settings.

A better reference for the stock exchanges would be just to use the local
fixed timezone.   EST isn't it.

Hope this helps,

Art
