### ISSUE TITLE
ConvertMismatch Argument Exception Being Thrown When Converting local timezone DateTime to utc, passing in local timezone

### ISSUE THREAD

**Issue by gregsaab** [mj1856/TimeZoneConverter#54]
Usage:
I have this extension method to convert datetimes to utc:

```
public static DateTime ToUtc(this DateTime dateTime, string timezoneName)
        {
            var timeZone = TZConvert.GetTimeZoneInfo(timezoneName);
            return TimeZoneInfo.ConvertTimeToUtc(dateTime, timeZone);
        }

```

I live in the EST, so this test will result in an ArgumentException(SR.Argument_ConvertMismatch)
```
var dateTime = DateTime.Now;
var utc = dateTime.ToUtc("Eastern Standard Time");
```

It seems that the issue is that the GetCorrespondingKind method is not properly identifying the timezone supplied as being the local, even though it is the local. 
![image](https://user-images.githubusercontent.com/2085647/62554026-6a27ff00-b83e-11e9-85ac-e31cda7a52be.png)
Seems that this could be an issue of == vs .Equals().

**Comment by mj1856** [comment]
This isn't an issue with `TimeZoneConverter`, but rather with the implementation of `TimeZoneInfo.CacheData.GetCorrespondingKind` internal method.

Also, the behavior you describe is documented in the comments for this method, both in [the .NET Framework Reference Source](https://referencesource.microsoft.com/#mscorlib/system/timezoneinfo.cs,ad15c48eb3ed57bc), and in the [.NET Core source code on GitHub](https://github.com/dotnet/corefx/blob/ea8557901ef8976238690872160b5b885fe08a31/src/Common/src/CoreLib/System/TimeZoneInfo.cs#L113-L140).

You could change your extension method to overcome this, as follows:

```csharp
public static DateTime ToUtc(this DateTime dateTime, string timezoneName)
{
    var timeZone = TZConvert.GetTimeZoneInfo(timezoneName);

    if (timeZone.Id == TimeZoneInfo.Local.Id)
    {
        timeZone = TimeZoneInfo.Local;
    }
    else if (timeZone.Id == TimeZoneInfo.Utc.Id)
    {
        timeZone = TimeZoneInfo.Utc;
    }
    
    return TimeZoneInfo.ConvertTimeToUtc(dateTime, timeZone);
}
```
