### ISSUE TITLE
Unable to translate TimeZone in .net core 3.0 - Alpine - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT disabled

### ISSUE THREAD

**Issue by seroche** [mj1856/TimeZoneConverter#56]
Hi,

We are migrating to .NET Core 3.0 and it's not a pleasant journey! 

Earlier we found out that EF core is now built on a library that does NOT support `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`.

To make it work, we had to disable this flag. After doing that and on Alpine Linux 3.9 we are unable to call `TZConvert.GetTimeZoneInfo(xxx)`. 

Regardless the value we send to this method, it throws an exception exception `System.TimeZoneNotFoundException`.

Calling `TZConvert.WindowsToIana(x.TimeZone)` still works as expected.

Seems that this piece of code is causing the issue:
![image](https://user-images.githubusercontent.com/12636347/65869131-5b784700-e3ac-11e9-9fde-b5be451564b8.png)

Any ideas?

Thx
Seb

**Comment by seroche** [comment]
i found out the root cause. Seems the tzdata package is missing.

I had to add the following line to my dockerfile:
RUN apk add --no-cache tzdata

**Comment by mj1856** [comment]
Makes sense.  Glad you found a solution.
