### ISSUE TITLE
Support for the Europe/Kyiv timezone

### ISSUE THREAD

**Issue by jankratochvilcz** [mj1856/TimeZoneConverter#57]
Steps to reproduce:
1. Call `TZConvert.GetTimeZoneInfo("Europe/Kyiv")`

Expected: Returns a timezone equivalent to "Europe/Kiev"
Actual: Throws `TimeZoneNotFoundException`

Here's a short article clarifying why this is a relevant issue: https://www.euronews.com/2019/06/21/kyiv-or-kiev-why-does-it-matter-so-much-to-ukrainians

**Comment by jankratochvilcz** [comment]
This is an invalid issue since Europe/Kyiv is not recognized by IANA:

> # From Paul Eggert (2018-10-03):
> # As is usual in tzdb, Ukrainian zones use the most common English spellings.
> # For example, tzdb uses Europe/Kiev, as "Kiev" is the most common spelling in
> # English for Ukraine's capital, even though it is certainly wrong as a
> # transliteration of the Ukrainian "Київ".  This is similar to tzdb's use of
> # Europe/Prague, which is certainly wrong as a transliteration of the Czech
> # "Praha".  ("Kiev" came from old Slavic via Russian to English, and "Prague"
> # came from old Slavic via French to English, so the two cases have something
> # in common.)  Admittedly English-language spelling of Ukrainian names is
> # controversial, and some day "Kyiv" may become substantially more popular in
> # English; in the meantime, stick with the traditional English "Kiev" as that
> # means less disruption for our users.

https://www.iana.org/time-zones

**Comment by ZimM-LostPolygon** [comment]
@jankratochvilcz Any update on this? Europe/Kyiv is valid as of 2022:
https://tracker.moodle.org/browse/MDL-75641
