### ISSUE TITLE
Do I need this with NodaTime?

### ISSUE THREAD

**Issue by Svetomechc** [mj1856/TimeZoneConverter#58]
Just not sure if this library is only for BCl or not.

**Comment by mj1856** [comment]
Depends on what you want to do.  Noda Time has CLDR mappings exposed in the tzdb time zone provider.  You could use the functions shown [here](https://stackoverflow.com/revisions/17348822/11) (under "Original Solution from 2013...") to do conversions.  I think I've made things easier with this library though.

**Comment by Svetomechc** [comment]
@mj1856 got it, thx!
