### ISSUE TITLE
How to get the current Windows Time Zone Id?

### ISSUE THREAD

**Issue by DamianMehers** [mj1856/TimeZoneConverter#59]
Hi,

I've been trying 

``` C#
TimeZoneConverter.TZConvert.TryWindowsToIana(TimeZoneInfo.Local.Id, out var ianaTimeZoneName);
```

This fails for my current timezone ("Europe/Zurich") ... The examples in the home page show passing in string values.  Do you have any guidance on how to get the current Windows Timezone Id?

I'm using Xamarin / iOS FWIW.

Thanks,
    Damian

**Comment by DamianMehers** [comment]
D'oh ... it was already an IANA timezone.  This complicates my NetStandard library code a little - I think I'll go with first checking `TZConvert.KnownIanaTimeZoneNames.Contains(TimeZoneInfo.Local.Id)` and if that fails then doing the `TryWindowsToIana`

**Comment by mj1856** [comment]
Sure.

Another way would be like this:

```csharp
using System;
using System.Runtime.InteropServices;
using TimeZoneConverter;

//...

string id = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) 
    ? TimeZoneInfo.Local.Id 
    : TZConvert.IanaToWindows(TimeZoneInfo.Local.Id);
```
