### ISSUE TITLE
Antarctica/Troll doesn't map

### ISSUE THREAD

**Issue by gregsdennis** [mj1856/TimeZoneConverter#61]
So far this is the only Olson TZ I've found that doesn't have a map to a Windows TZ.  I *think* it could be European Standard (UTC+1).  It's in line (same-ish longitude) with Paris, but I doubt the location would be affected by daylight saving time.

https://www.google.com/maps/place/Troll+Station/@-22.9806485,-1.8199189,3z/data=!4m5!3m4!1s0xb0a133f229025b2b:0x53a2ef030bcb54da!8m2!3d-72.0124876!4d2.5322199

**Comment by mj1856** [comment]
`Antartctica/Troll` has no Windows equivalent.  It is the only one.

It currently switches between UTC and UTC+2.  It used to (between 2005 to 2015) switch between *three* different offsets.

See also #31.

**Comment by gregsdennis** [comment]
Can this library map it to one of those by default? Alternatively, can you add an override method so that I can map it in my application?

**Comment by mj1856** [comment]
There's no ID to map it to, so it can't just return one of them.  Neither options would be correct.

However I will consider allowing the methods that return a `TimeZoneInfo` object to use a custom time zone in such case.  Tracking in #62
