### ISSUE TITLE
Unsupported timezone

### ISSUE THREAD

**Issue by yakimko** [mj1856/TimeZoneConverter#63]
There is a timezone Canada/East-Saskatchewan which became unsupported
https://stackoverflow.com/questions/47618861/error-invalid-value-for-parameter-timezone-canada-east-saskatchewan

**Comment by mj1856** [comment]
This is already accounted for.  

```csharp
string tz = TZConvert.IanaToWindows("Canada/East-Saskatchewan");
// "Canada Central Standard Time"
```

**Comment by yakimko** [comment]
But can you exclude it from KnownIanaTimeZoneNames dictionary?
