### ISSUE TITLE
Samoa Standard Time issue?

### ISSUE THREAD

**Issue by nbalu** [mj1856/TimeZoneConverter#66]
Hi Matt!

I've run into a very interesting issue.

![image](https://user-images.githubusercontent.com/7927881/78341798-8c724800-7598-11ea-81c1-5d2274ef566b.png)

Samoa Standard Time in my opinion should be Midway Atoll (GMT-11).

I know, that windows is not listing midway and UTC-11 "became that timezone" but the identifiers seems to be changed in the meanwhile and SST became Pacific/Apia. 

So who's right? 🤣

System info:
![image](https://user-images.githubusercontent.com/7927881/78342650-e0c9f780-7599-11ea-97ba-589011db4b2d.png)

**Comment by mj1856** [comment]
The data is correct.  See my writeup on StackOverflow here https://stackoverflow.com/a/55150303/634824
