### ISSUE TITLE
Can we add a strong name signing key to this assembly?

### ISSUE THREAD

**Issue by LammyL** [mj1856/TimeZoneConverter#7]
Can we add a strong name signing key to this assembly?  I can't reference the nuget package from any assembly that is signed because this assembly isn't signed.

**Comment by danman226** [comment]
Second on the strong name. Nice library, would love to use if it had a strong name.

**Comment by MattFromGer** [comment]
His answer regarding this:
`I don't strong name any of my nuget packages. If you want strong naming, there are several ways to do that yourself.`
[https://github.com/mj1856/TimeZoneConverter/issues/5](url)

**Comment by mj1856** [comment]
Yes, thanks.  Closing as dup of #5.

Also, please read:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/
