### ISSUE TITLE
Incorrect Iana to Windows mapping

### ISSUE THREAD

**Issue by MiroslavGrozdanovski** [mj1856/TimeZoneConverter#72]
Calling the following function:

`TZConvert.IanaToWindows("Europe/Skopje")`

returns "Central Europe Standard Time" instead of "Central European Standard Time".

According to Windows, the latter is the correct one, since:

Central Europe Standard Time = Belgrade, Bratislava, Budapest, Ljubljana, Prague
Central European Standard Time = Sarajevo, Skopje, Warsaw, Zagreb

Is this an issue within the library mapping?

Thank you!

**Comment by mj1856** [comment]
There does indeed to be an issue here.  I'll investigate.  Thanks!

**Comment by mj1856** [comment]
What's happening here is that `Europe/Skopje` is an IANA link to `Europe/Belgrade` - which is mapped to a different Windows zone in CLDR.  The two Windows zones are essentially the same - so there's no damage being done.  But it should indeed be more precise.  I will change the mappings to only follow links when a direct mapping doesn't already exist.
