### ISSUE TITLE
Could not load file or assembly 'TimeZoneConverter, Version=2.2.0.0

### ISSUE THREAD

**Issue by Hiren-Vyas** [mj1856/TimeZoneConverter#73]
Hello Team,
I am using TimeZoneConverter, Version=2.2.0.0 in .net core 2.2 project its work fine in my local Mac envirement.but when I push my code with Publish in windows server its throw below error.

{"error":{"description":"Could not load file or assembly 'TimeZoneConverter, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.\n   at HelloHealthy.Domain.Entities.Helper.StaticHelpers.GetLocalTime(DateTimeOffset dateTime, String timeZoneId)\r\n   at HelloHealthy.API.Controllers.TestController.SendTestEmail(String Email, String requestId)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at HelloHealthy.API.Middleware.GCMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)"}}

**Comment by mj1856** [comment]
Hi, sorry for the delayed response.
Please show steps to reproduce the issue.  Others are not reporting this, so it's likely not something related to the library itself.

**Comment by mj1856** [comment]
Closing this, but if you are still having problems then please add supporting details and I'll reopen.  Thanks.
