### ISSUE TITLE
TZConvert.IanaToWindows("America/Nuuk") fails

### ISSUE THREAD

**Issue by OlsonDev** [mj1856/TimeZoneConverter#74]
I have no clue what it should be, but I did notice it.

**Comment by mj1856** [comment]
Thanks.  `America/Nuuk` is a link that should resolve to `America/Godthab` before mapping to `Greenland Standard Time`.  I can confirm that it isn't working.  I'll check it out.  Thanks for reporting!

**Comment by ChristianRMKoerber** [comment]
Funny, I ran into the same issue today because for whatever reasons I chose Greenland for testing.

**Comment by mj1856** [comment]
Fixed after updating data.  Resolved in version 3.3.0.

Thanks!
