### ISSUE TITLE
Inconsistency between Windows and Linux

### ISSUE THREAD

**Issue by xlegalles** [mj1856/TimeZoneConverter#78]
**Reproducible steps**
This code works fine under Windows 10 (.NET Core 2.2) but not under Ubuntu:
```
var can = TZConvert.TryGetTimeZoneInfo("Europe/Paris", out var timeZone);
if (can)
{
       Console.WriteLine($"TZ  Europe/Paris into IANA {TZConvert.WindowsToIana(timeZone.Id)}");
}
```
**Current result**
```
Unhandled Exception: System.InvalidTimeZoneException: "Europe/Paris" was not recognized as a valid Windows time zone ID.
   at TimeZoneConverter.TZConvert.WindowsToIana(String windowsTimeZoneId, String territoryCode)
```

Any idea?

**Comment by xlegalles** [comment]
So the `WindowsToIana `is not the problem as of course, the entry for "Europe/Paris" exists for both OS.

The problem is from the `TryGetTimeZoneInfo `which is not consistent between OS: in Windows it gives "Romance Standard Time" as an Id, whereas in Ubuntu it gives "Europe/Paris".

**Comment by mj1856** [comment]
You might be missing `tzdata` on your system.  Can you do a `sudo apt-get install tzdata` and try again?

Even so, you've highlighted a minor bug here either way, as the error message shouldn't say it's a Windows ID.  I can fix that.  Thanks.

**Comment by mj1856** [comment]
I created #79 to track the bug with the error message.  It may be a bit before I get to that.  Let me know if installing `tzdata` solved your original issue.

**Comment by mj1856** [comment]
`TryGetTimeZoneInfo` returns a `TimeZoneInfo` object - which is platform specific by nature.   The error isn't there, but in the second part where you call `WindowsToIana`, presuming the `Id` will be a Windows one.  As you pointed out, it won't be - but rather it will be platform specific.

You should just print the `timeZone.Id` in the second part - there's no purpose in converting there.

**Comment by xlegalles** [comment]
Just to explain the purpose: we don't know what is the input. It can be a IANA or Windows time zone id. I thought that a good way to standardize this was using TZConvert.TryGetTimeZoneInfo which is able to work with both. But at the end, we want to store a IANA code and this is why we finally do a TZConvert.WindowsToIana
I know there are other ways of doing it and I have already implemented another solution which works on both OS. 

Just to mention that it is not obvious that TimeZoneInfo is system specific and I don't see any warning from MS about that: all makes you believe that this is consistent across OS. It should be worth mentioning it in your documentation.
