### ISSUE TITLE
[Feature Request?] Convert from country code e.g. "UK" to TimeZoneInfo

### ISSUE THREAD

**Issue by MattFromGer** [mj1856/TimeZoneConverter#8]
Hey Matt,

in my application I need to (as a fallback) convert from a two- or three letter country code to a TimeZoneInfo object if there is no iana information available.
The thing is, I theoretically could already do this with your existing Mapping.csv, since the second field is the territory code. I did some tests and extended your code with a new `Dictionary<string, IList<string>()` which holds the country code as the key and a list of iana timezones as value.

Result is: It works, but it's not perfect. Because the iana DB uses the code "001" as the regions main used timezone. Thus it actually would make sense to use this "001" timezone for a country instead of a dirty "FirstOrDefault()" of my list above (which disregards all the "001" zones).

So my question: Do you think it makes sense to provide this information in your library?

P.S. Going in the direction of this .json example: 
```json
{
	"IsoAlpha3": "ZAF",
	"TimeZones": ["Africa/Johannesburg"],
	"WindowsTimeZones": [{
		"Id": "South Africa Standard Time",
		"Name": "(UTC+02:00) Harare, Pretoria"
	}],
	"CountryName": "South Africa",
	"IsoAlpha2": "ZA"
},
{
	"IsoAlpha3": "ESP",
	"TimeZones": ["Europe/Madrid",
	"Africa/Ceuta",
	"Atlantic/Canary"],
	"WindowsTimeZones": [{
		"Id": "Romance Standard Time",
		"Name": "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris"
	},
	{
		"Id": "GMT Standard Time",
		"Name": "(UTC+00:00) Dublin, Edinburgh, Lisbon, London"
	}],
	"CountryName": "Spain",
	"IsoAlpha2": "ES"
},
....
```

**Comment by mj1856** [comment]
Hi, and sorry for the delay.  I think what you're looking for is in my [TimeZoneNames ](https://github.com/mj1856/TimeZoneNames)library presently:

```
public static string[] GetTimeZoneIdsForCountry(string countryCode)
```

This returns IANA time zones, which you could then use with TimeZoneConverter to get the corresponding Windows IDs, then a simple `Distinct` using linq.

I will think about adding such a method in this library as well, or perhaps deprecating it there and doing it here instead.

Oh, BTW - the ISO country code for the United Kingdom is `GB`, not `UK`, and I don't have support for the three-letter ISO codes in either library yet.  If you think that's important, please raise another issue with a feature request.

Cheers!

**Comment by MattFromGer** [comment]
Perfect, thank you!
If you add it here as well, it would be good if you give the "001" info a higher priority (if existing).
Because right now (even in your TimeZoneNames lib - correct me if I'm wrong) 001 seems to be its own country with several timezones.

**Comment by mj1856** [comment]
"001" is in the source data from CLDR.  It refers to the IANA zone that is chosen for a given Windows zone when there is no country code provided.

http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml

http://www.unicode.org/reports/tr35/tr35-dates.html#Windows_Zones
