### ISSUE TITLE
TZConvert not working on Xamarin:Android platform

### ISSUE THREAD

**Issue by michalsedlak** [mj1856/TimeZoneConverter#80]
Hi,

I would like to ask you for help with TimeZoneConverter(v 3.3.0) library running on Xamarin.Android(SDK v11.1.0.17).

I need to convert timezone from Windows format to IANA format but on Xamarin.Android platform I always receive TimeZoneNotFoundException.

Even if I call these simple calls the exception is thrown:

`bool res1 = TZConvert.TryIanaToWindows("America/Denver", out string iana1);`
or
`bool res2 = TZConvert.TryWindowsToIana("Eastern Standard Time", out string iana2);`

Can I use this library with Xamarin? The application runs also on UWP and there is no such issue, it happens only on Android device.

Thank you for your help.

Regards,
Michal

**Comment by mj1856** [comment]
Yes, you should be able to use it with Xamarin on Android, as long as tzdata is available.  Some info on how Android get tzdata here:  https://source.android.com/devices/tech/config/timezone-rules

There's only one place in *this* library where `TimeZoneNotFoundException` is thrown, which is [here](https://github.com/mj1856/TimeZoneConverter/blob/3e9d0363b4c986e9d8cb9f388fb91210bdc86167/src/TimeZoneConverter/TZConvert.cs#L151), when calling `TZConvert.GetTimeZoneInfo` on a platform targeting .NET Stanadard lower than 1.3 - which shouldn't be hardly anywhere anymore.

Is it  possible you are getting the exception from some *other* code?  For example, do you call `TimeZoneInfo.FindSystemTimeZoneById`?

**Comment by michalsedlak** [comment]
After investigation I found out that the problem described above happens only in debug mode. It looks like the static ctor of TZConvert class is not executed and properties like `KnownIanaTimeZoneNames` are not initialized. If I put a breakpoint just before the `TZConvert.TryIanaToWindows("America/Denver", out string iana1);` call and manually evaluate `TZConvert.KnownIanaTimeZoneNames` property the application is working fine. Without this evaluation it's crashing in debug mode. Seems to be a kind of configuration issue or feature of Xamarin .net debugger.

**Comment by mj1856** [comment]
Can you please copy/paste the entire exception including message and stack trace?  Thanks.

**Comment by michalsedlak** [comment]
Yes, I will provide.

**Comment by michalsedlak** [comment]
Hi,
I'm trying to reproduce the issue but for some reason it's still working fine and I'm not able to reproduce either on Android table or simulator. I'm sorry but it looks like I had an issue on my environment and now it's somehow resolved.

**Comment by mj1856** [comment]
No worries.  I'll close the issue then.  If you can reproduce we can re-open.
