### ISSUE TITLE
Yukon Standard Time .GetTimeZoneInfo error

### ISSUE THREAD

**Issue by jag-s-n** [mj1856/TimeZoneConverter#81]
Hello,

At the moment I'm selecting out a list of KnownWindowsTimeZoneIds and use the GetTimeZoneInfo to convert to a list of TimeZoneInfo list.

However TZConvert.GetTimeZoneInfo("Yukon Standard Time") fails and creates an error.

Yukon Standard Time seems to return in the KnownWindowsTimeZoneIds but does not parse on a Windows Azure App Service

I'm on 3.3.0 Timezone Converter.

**Comment by mj1856** [comment]
It would appear that Azure App Service does not yet have the Yukon Standard Time time zone installed.  I will contact the responsible team to ask for it to be added.

See my comments in #49 about how their servicing process works.

**Comment by mj1856** [comment]
I was informed that this is scheduled to be updated in the Azure Guest OS image (and App Service accordingly) near the beginning of 2021.  If it is urgent for you, then I suggest raising a support ticket.  I'm closing the issue here as there's nothing more to do for this library.
