### ISSUE TITLE
TimeZoneInfo on MacOS

### ISSUE THREAD

**Issue by derekantrican** [mj1856/TimeZoneConverter#84]
I have an application that has been running in WinForms (on Windows, of course) for a few years. I have been using the following code to get a `TimeZoneInfo` object from an IANA string:

```csharp
TimeZoneInfo.FindSystemTimeZoneById(TZConvert.IanaToWindows("Europe/Zurich"))
```

Now that I am trying to port my application to .NET Core (using the [Avalonia Framework](https://github.com/AvaloniaUI/Avalonia)) I am discovering that this line of code seems to hang indefinitely on MacOS. Troubleshooting shows that it's caused by the `FindSystemTimeZoneById` method - I imagine this method is specific to Windows?

Is there a better or more recommended way to retrieve a `TimeZoneInfo` object from an IANA string? I'm aware there is `TimeZoneInfo.FromSerializedString(string)` but I am not sure if that's what I'm looking for.

**Comment by derekantrican** [comment]
My bad - I looked at TimeZoneInfo and for some reason thought it was part of this project (and not built into System).

After doing some digging - is `TZConvert.GetTimeZoneInfo(id)` the recommended way to generate a `TimeZoneInfo` object on MacOS?

**Comment by mj1856** [comment]
Hi.  A few things:

- Yes, `TimeZoneInfo` is part of .NET.  [Docs are here](https://docs.microsoft.com/dotnet/api/system.timezoneinfo).  It is currently *system specific*, meaning that on Windows systems it uses Windows time zones, and on non-Windows systems it uses IANA time zones.
- This library, TimeZoneConverter, is focused on providing correct translation between Windows and IANA time zone identifiers, to make cross-platform development possible.
- `TZConvert.IanaToWindows("Europe/Zurich")` will *always* give `"W. Europe Standard Time"`.  You're asking for a Windows zone.  It doesn't matter what OS you run that on, you will get the same result.
- If you run `TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time")` on a non-Windows system, it should throw a `TimeZoneNotFoundException`, not hang.  If it's hanging, there's likely something else going on in your own code to cause that.
- Yes, using `TZConvert.GetTimeZoneInfo` or `TzConvert.TryGetTimeZoneInfo` is the recommended approach.  They both will load the appropriate time zone information for the running platform regardless of which form of identifier you pass.  That way you can write your code once, and deploy to any platform (as long as the platform has time zone data present, some Linux distros do not include it by default).

**Comment by derekantrican** [comment]
Thanks for all the useful info. So would you say that these are both the recommended methods?

```csharp
public static Timezone FromId(string id)
{
    if (id == "Default" || string.IsNullOrEmpty(id))
    {
        return new Timezone(null);
    }
    else
    {
        return new Timezone(TZConvert.GetTimeZoneInfo(id));
    }
}

public string IANA
{
    get
    {
        if (IsDefault)
        {
            return null;
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            return TZConvert.WindowsToIana(timeZoneInfo.Id);
        }
        else
        {
            return timeZoneInfo.Id;
        }
    }
}
```

**Comment by mj1856** [comment]
Not sure why you need your own `Timezone` class or what the "default" actually does, but that aside it looks fine.  The only thing you might consider is that there are several different IANA zones that are covered by each Windows zone, so you may want to retain the ID provided if there's an expectation of the `IANA` property always matching the `id` passed to `FromId` when running on Windows.

**Comment by mj1856** [comment]
Take a look at the source data in CLDR, and I think you'll understand.
https://github.com/unicode-org/cldr/blob/master/common/supplemental/windowsZones.xml

For example, `America/Vancouver` => `Pacific Standard Time` => `America/Los_Angeles`

**Comment by derekantrican** [comment]
Yeah, I have created my own class to simplify some code throughout my project, to handle that "default" case, and to somewhat "combine" TZConvert & TimeZoneInfo into a single class.

I'm aware of the IANA -> Windows -> IANA issues you mentioned, but I'll doublecheck my code. Thanks for the advice!
