### ISSUE TITLE
"US/Pacific" was not recognized as a valid Windows time zone ID.

### ISSUE THREAD

**Issue by vladkuz** [mj1856/TimeZoneConverter#86]
We are getting this exception when running in Debian docker image. 
```
System.InvalidTimeZoneException: "US/Pacific" was not recognized as a valid Windows time zone ID.
   at TimeZoneConverter.TZConvert.WindowsToIana(String windowsTimeZoneId, String territoryCode)
```

Nuget version 3.3.0

**Comment by mj1856** [comment]
Well, that's correct.  `US/Pacific` is an IANA ID, not a Windows ID.  The exception shows you are calling `WindowsToIana`.

You either need to call `IanaToWindows`, or if your intent is to get a `TimeZoneInfo` object, then use `GetTimeZoneInfo`.

If you'd like additional help, please show the code you are using.  Thanks.
