### ISSUE TITLE
Is there a method to get all timezones  ?

### ISSUE THREAD

**Issue by sajeetharan** [mj1856/TimeZoneConverter#9]
Probably not an issue, but Is there a method to get all timezones  ?

**Comment by mj1856** [comment]
Yes.  I should add them to the readme, but depending on which type you want, you can use any of:

```csharp
TZConvert.KnownIanaTimeZoneNames
TZConvert.KnownWindowsTimeZoneIds
TZConvert.KnownRailsTimeZoneNames
```
